#! /bin/sh

# we need both interfaces connected, so drop out if the other one is not
# attached to the slot yet
if ! snapctl is-connected raw-usb; then
  echo "please run 'snap connect ${SNAP_NAME}:raw-usb"
  echo
  echo "keeping service disabled for the moment"
  exit 0
fi

# now we can start the service
if snapctl services ${SNAP_NAME}.pcscd | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.pcscd 2>&1 || true
fi
